on:
  release:
    types:
      - published
  workflow_dispatch:  
    
name: release-3rdparty
jobs:   
  build:
    runs-on: ubuntu-latest
    name: build-and-testing
    env:
      JRELEASER_SDKMAN_CONSUMER_KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
      JRELEASER_SDKMAN_CONSUMER_TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}
      JRELEASER_TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      JRELEASER_TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      JRELEASER_TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      JRELEASER_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      JRELEASER_BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      JRELEASER_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      JRELEASER_MAVENCENTRAL_JBANG_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      JRELEASER_MAVENCENTRAL_JBANG_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      JRELEASER_DOCKER_DEFAULT_PASSWORD: notusedbutrequiredbyjreleaser
      JRELEASER_VERSION: 1.19.0
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0
    
      - name: Install container-structure-test
        run: |
          curl -LO https://github.com/GoogleContainerTools/container-structure-test/releases/latest/download/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          mkdir -p $HOME/.local/bin
          mv container-structure-test-linux-amd64 bin
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Login to docker hub
        if: success()
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Quay.io
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Login to github
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: install-java11
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: setup-gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4
      - name: build-gradle
        run: ./gradlew --no-daemon clean build -x test --build-cache --scan -s
      - name: version extract
        id: version
        run: |
          RELEASE_VERSION=`cat build/tmp/version.txt`
          echo "::set-output name=RELEASE_VERSION::$RELEASE_VERSION"
      - name: jreleaser publish
        continue-on-error: true
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_PROJECT_VERSION: ${{steps.version.outputs.RELEASE_VERSION}}
        with:
          version: ${{ env.JRELEASER_VERSION }}
          arguments: publish
          setup-java: false
      - name: JReleaser publish output
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: jreleaser-publish
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
      - name: spec
        continue-on-error: true
        env:
          BREW_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
          BREW_USER: ${{ secrets.BREW_USER }}
        run: ./misc/updatespec.sh
      - name: jreleaser announce
        continue-on-error: true
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_PROJECT_VERSION: ${{steps.version.outputs.RELEASE_VERSION}}
        with:
          version: ${{ env.JRELEASER_VERSION }}
          arguments: announce
          setup-java: false
      - name: JReleaser announce output
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: jreleaser-announce
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
      - name: upload-choco
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: build-choco
          path: build/choco
  choco:
    needs: build
    runs-on: windows-latest
    name: publish-choco
    continue-on-error: true
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: build-choco
          path: build/choco
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: '2.2.204' # SDK Version to use.
      - name: choco-build
        run: |
          powershell
          choco pack build/choco/jbang.nuspec
      - name: github-nuget
        continue-on-error: true
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          powershell
          dotnet nuget source add -username maxandersen --password $GITHUB_TOKEN --store-password-in-clear-text --name github "https://nuget.pkg.github.com/maxandersen/index.json"
          dotnet nuget push $(ls *.nupkg | % {$_.FullName}) --source github
      - name: choco-publish
        continue-on-error: true
        run: |
          powershell
          choco apikey -k ${{ secrets.CHOCO_API_KEY }} -source https://push.chocolatey.org/
          choco push $(ls *.nupkg | % {$_.FullName}) -s https://push.chocolatey.org/
