on:
  release:
    types:
      - published

name: release-3rdparty
jobs:
  build:
    runs-on: ubuntu-latest
    name: build-and-testing
    steps:
      - uses: actions/checkout@v1
      - name: install-java11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build-gradle
        run: ./gradlew clean build -x test --build-cache --scan -s
      - name: docker
        continue-on-error: true
        env:
          BREW_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
          BREW_USER: ${{ secrets.BREW_USER }}
        run: ./misc/updatecontainer.sh
      - name: homebrew
        continue-on-error: true
        env:
          BREW_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
          BREW_USER: ${{ secrets.BREW_USER }}
        run: ./misc/updatebrew.sh
      - name: scoop
        continue-on-error: true
        env:
          BREW_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
          BREW_USER: ${{ secrets.BREW_USER }}
        run: ./misc/updatescoop.sh
      - name: spec
        continue-on-error: true
        env:
          BREW_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
          BREW_USER: ${{ secrets.BREW_USER }}
        run: ./misc/updatespec.sh
      - name: snap
        continue-on-error: true
        env:
          BREW_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
          BREW_USER: ${{ secrets.BREW_USER }}
        run: ./misc/updatesnap.sh
      - name: sdkman
        continue-on-error: true
        env:
          SDKMAN_CONSUMER_KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
          SDKMAN_CONSUMER_TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}
        run: ./misc/updatesdkman.sh
      - name: upload-choco
        uses: actions/upload-artifact@v1
        with:
          name: build-choco
          path: build/choco
  choco:
    needs: build
    runs-on: windows-latest
    name: publish-choco
    continue-on-error: true
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: build-choco
          path: build/choco
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.204' # SDK Version to use.
      - name: choco-build
        run: |
          powershell
          choco pack build/choco/jbang.nuspec
      - name: github-nuget
        continue-on-error: true
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          powershell
          dotnet source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/maxandersen/index.json"
          dotnet nuget setApiKey $GITHUB_TOKEN -Source "GitHub"
          dotnet nuget push $(ls *.nupkg | % {$_.FullName}) --source "GitHub"
      - name: choco-publish
        continue-on-error: true
        run: |
          powershell
          choco apikey -k ${{ secrets.CHOCO_API_KEY }} -source https://push.chocolatey.org/
          choco push $(ls *.nupkg | % {$_.FullName}) -s https://push.chocolatey.org/
  snapcraft:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Snapcraft Action
        uses: samuelmeuli/action-snapcraft@v1.2.0
        with:
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}
      - name: Sleep
        run: sleep 1200
      - name: Promote
        run: ./misc/promotesnap.sh