on:
  release:
    types:
      - published

name: release-3rdparty
jobs:   
  build:
    runs-on: ubuntu-latest
    name: build-and-testing
    env:
      JRELEASER_SDKMAN_CONSUMER_KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
      JRELEASER_SDKMAN_CONSUMER_TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}
      JRELEASER_TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      JRELEASER_TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      JRELEASER_TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      JRELEASER_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      JRELEASER_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      JRELEASER_VERSION: 0.9.0
    steps:
      - uses: actions/checkout@v3
      - name: install-java11
        uses: actions/setup-java@v3
        with:
          java-version: 11
      - name: build-gradle
        run: ./gradlew --no-daemon clean build -x test --build-cache --scan -s
      - name: version extract
        id: version
        run: |
          RELEASE_VERSION=`cat build/tmp/version.txt`
          echo "::set-output name=RELEASE_VERSION::$RELEASE_VERSION"
      - name: jreleaser publish
        continue-on-error: true
        uses: jreleaser/release-action@v1
        env:
          JRELEASER_PROJECT_VERSION: ${{steps.version.outputs.RELEASE_VERSION}}
        with:
          version: ${{ env.JRELEASER_VERSION }}
          arguments: publish
      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-publish
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
      - name: spec
        continue-on-error: true
        env:
          BREW_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
          BREW_USER: ${{ secrets.BREW_USER }}
        run: ./misc/updatespec.sh
      - name: jreleaser announce
        continue-on-error: true
        uses: jreleaser/release-action@v1
        env:
          JRELEASER_PROJECT_VERSION: ${{steps.version.outputs.RELEASE_VERSION}}
        with:
          version: ${{ env.JRELEASER_VERSION }}
          arguments: announce
      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-announce
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
      - name: upload-choco
        uses: actions/upload-artifact@v3
        with:
          name: build-choco
          path: build/choco
  choco:
    needs: build
    runs-on: windows-latest
    name: publish-choco
    continue-on-error: true
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-choco
          path: build/choco
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '2.2.204' # SDK Version to use.
      - name: choco-build
        run: |
          powershell
          choco pack build/choco/jbang.nuspec
      - name: github-nuget
        continue-on-error: true
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          powershell
          dotnet nuget source add -username maxandersen --password $GITHUB_TOKEN --store-password-in-clear-text --name github "https://nuget.pkg.github.com/maxandersen/index.json"
          dotnet nuget push $(ls *.nupkg | % {$_.FullName}) --source github
      - name: choco-publish
        continue-on-error: true
        run: |
          powershell
          choco apikey -k ${{ secrets.CHOCO_API_KEY }} -source https://push.chocolatey.org/
          choco push $(ls *.nupkg | % {$_.FullName}) -s https://push.chocolatey.org/
