on:
  push:
    tags:
      - 'v*'

name: tag-and-release
jobs:
  check-debug:
    runs-on: ubuntu-latest
    outputs:
      debug_enabled: ${{ steps.check-msg.outputs.debug_enabled }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Extract tag commit message and set debug flag
        id: check-msg
        run: |
          msg=$(git log -1 --pretty=%B)
          echo "Commit message: $msg"
          if echo "$msg" | grep -iq "#debug"; then
            echo "debug_enabled=true" >> $GITHUB_OUTPUT
          else
            echo "debug_enabled=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-debug
    runs-on: ubuntu-latest
    name: build-and-testing
    env:
      JRELEASER_SDKMAN_CONSUMER_KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
      JRELEASER_SDKMAN_CONSUMER_TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}
      JRELEASER_TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      JRELEASER_TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      JRELEASER_TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      JRELEASER_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      JRELEASER_BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      JRELEASER_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      JRELEASER_MAVENCENTRAL_JBANG_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      JRELEASER_MAVENCENTRAL_JBANG_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      JRELEASER_VERSION: 1.19.0
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0
      - name: install-java11
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: setup-gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4
      - name: build-gradle
        run: ./gradlew --no-daemon clean build installDist publish --build-cache --scan -s
      - name: integration-test
        run: |
          ./gradlew integrationTest
      - name: integration-test-bash
        run: |
          export PATH=`pwd`/build/install/jbang/bin:$PATH
          pastdir=`pwd`
          cd itests
          ./test_suite.sh
          cd $pastdir
      - name: version extract
        id: version
        run: |
          RELEASE_VERSION=`cat build/tmp/version.txt`
          echo "::set-output name=RELEASE_VERSION::$RELEASE_VERSION"
      - name: Run JReleaser
        uses: jreleaser/release-action@v2
        env: 
          JRELEASER_PROJECT_VERSION: ${{steps.version.outputs.RELEASE_VERSION}}
        with:
          version: ${{ env.JRELEASER_VERSION }}
          arguments: release
          setup-java: false
      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
    
      - name: Start tmate session
        if: always() && needs.check-debug.outputs.debug_enabled == 'true'
        uses: mxschmitt/action-tmate@7b6a61a73bbb9793cb80ad69b8dd8ac19261834c # v3
        with:
            limit-access-to-actor: true
