on:
  push:
    tags:
      - 'v*'

name: tag-and-release
jobs:
  build:
    runs-on: ubuntu-latest
    name: build-and-testing
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: install-java11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build-gradle
        run: ./gradlew clean build --build-cache --scan -s
      - name: integration-test
        run: |
          export PATH=`pwd`/build/install/jbang/bin:$PATH
          pastdir=`pwd`
          cd itests
          ./test_suite.sh
          ./itests.sh
          cd $pastdir
      - name: tag-and-release
        env:
          ORG_GRADLE_PROJECT_github_token: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew githubRelease

